### ISSUE TITLE
Modularize the css

### ISSUE THREAD

**Issue by MadsRC** [picturepan2/devices.css#1]
Are you planning on supporting importing the individual devices as they are needed?

Kinda like (Bulma)[http://bulma.io/documentation/overview/modular/] with its `.sass` files - Would require everything to be rewritten as sass but I guess that would be easier to do early on?

**Comment by picturepan2** [comment]
@MadsRC Please check out the `src` folder. There are .scss files for each device.

**Comment by MadsRC** [comment]
Ah, yes, just saw that!

Awesome - Great library :D

**Comment by picturepan2** [comment]
@MadsRC Writing Readme for clear usage and future plans.
