### ISSUE TITLE
The iMac Pro broke the logo on the front panel.

### ISSUE THREAD

**Issue by ilyalesik** [picturepan2/devices.css#3]
Windows 10, Chrome 60.0.
![2017-09-26 22_44_42-devices css - modern devices in pure css](https://user-images.githubusercontent.com/1270648/30880785-61f23902-a30c-11e7-9181-a1bad08af633.png)

**Comment by picturepan2** [comment]
@ilyalesik I see. It is a Mac-only unicode.
