### ISSUE TITLE
Trying to put an mp4 file inside device-content

### ISSUE THREAD

**Issue by robinjeandesign** [picturepan2/devices.css#4]
Has anyone tried to show a video mp4 file inside the device-content. I tried adding it in index.html and also tried to replace background-image src file in css, but its an mp4, so of course this way didn't work either. 

Any suggestions or has anyone already successfully done this?

**Comment by picturepan2** [comment]
@robinjeandesign I have updated the demo. Please look at the page source code. https://picturepan2.github.io/devices.css/#iphone-x
